# Generated by Django 5.0 on 2023-12-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_alter_detail_options_alter_given_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="date_input_doc",
            field=models.DateField(
                blank=True,
                help_text="Укажите дату входящего документа",
                null=True,
                verbose_name="Дата входящего",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="date_output_doc",
            field=models.DateField(
                blank=True,
                help_text="Укажите дату исходящего документа",
                null=True,
                verbose_name="Дата исходящего",
            ),
        ),
    ]
